site_name: molecule_lib Documentation
site_url: https://jerschro.github.io/molecule_lib_documentation/
site_author: Jeremy Schroeder
site_description: Documentation of python library for manipulating molecular structures.
repo_name: jerschro/molecule_lib_documentation
repo_url: https://github.com/jerschro/molecule_lib_documentation

nav:
  - Home : index.md
  - Read Functions : read_functions.md
  - LAMMPS : lammps.md
  # - OLD API Reference : reference.md
  # - Todo Page: todo.md
  # - Report Bugs : submit_bug.md
  - Reference:
    - Home : reference/index.md
    - ABCCoord :
      - ABCCoord : reference/ABCCoord/ABCCoord.md
      - ABCCoord.line : reference/ABCCoord/line.md
    - LatticeMatrix :
      - LatticeMatrix : reference/LatticeMatrix/LatticeMatrix.md
      - LatticeMatrix.getabc : reference/LatticeMatrix/getabc.md
      - LatticeMatrix.getanglesdeg : reference/LatticeMatrix/getanglesdeg.md
      - LatticeMatrix.getanglesrad : reference/LatticeMatrix/getanglesrad.md
    - ABCMolecule :
      - ABCMolecule : reference/ABCMolecule/ABCMolecule.md
      - ABCMolecule.add_coords : reference/ABCMolecule/add_coords.md
      - ABCMolecule.append : reference/ABCMolecule/append.md
      - ABCMolecule.convert : reference/ABCMolecule/convert.md
      - ABCMolecule.delete : reference/ABCMolecule/delete.md
      - ABCMolecule.format : reference/ABCMolecule/format.md
      - ABCMolecule.freeze_atoms : reference/ABCMolecule/freeze_atoms.md
      - ABCMolecule.generate_supercell : reference/ABCMolecule/generate_supercell.md
      - ABCMolecule.get_centroid : reference/ABCMolecule/get_centroid.md
      - ABCMolecule.info : reference/ABCMolecule/info.md
      - ABCMolecule.manipulate : reference/ABCMolecule/manipulate.md
      - ABCMolecule.move : reference/ABCMolecule/move.md
      - ABCMolecule.printt : reference/ABCMolecule/printt.md
      - ABCMolecule.rotate : reference/ABCMolecule/rotate.md
      - ABCMolecule.save : reference/ABCMolecule/save.md
      - ABCMolecule.sort : reference/ABCMolecule/sort.md
    - XYZCoord :
      - XYZCoord : reference/XYZCoord/XYZCoord.md
      - XYZCoord.line : reference/XYZCoord/line.md
    - XYZMolecule :
      - XYZMolecule : reference/XYZMolecule/XYZMolecule.md
      - XYZMolecule.add_coords : reference/XYZMolecule/add_coords.md
      - XYZMolecule.append : reference/XYZMolecule/append.md
      - XYZMolecule.convert : reference/XYZMolecule/convert.md
      - XYZMolecule.delete : reference/XYZMolecule/delete.md
      - XYZMolecule.format : reference/XYZMolecule/format.md
      - XYZMolecule.generate_supercell : reference/XYZMolecule/generate_supercell.md
      - XYZMolecule.get_centroid : reference/XYZMolecule/get_centroid.md
      - XYZMolecule.info : reference/XYZMolecule/info.md
      - XYZMolecule.manipulate : reference/XYZMolecule/manipulate.md
      - XYZMolecule.move : reference/XYZMolecule/move.md
      - XYZMolecule.printt : reference/XYZMolecule/printt.md
      - XYZMolecule.rotate : reference/XYZMolecule/rotate.md
      - XYZMolecule.save : reference/XYZMolecule/save.md
      - XYZMolecule.sort : reference/XYZMolecule/sort.md
    - Functions :
      - Functions : reference/functions/index.md
      - _determine_rest_of_xsf_file : reference/functions/_determine_rest_of_xsf_file.md
      - _is_ae : reference/functions/_is_ae.md
      - _is_xsf_coord_line : reference/functions/_is_xsf_coord_line.md
      - _isfloatstr : reference/functions/_isfloatstr.md
      - _regex_nested_string_list : reference/functions/_regex_nested_string_list.md
      - _regex_string_list : reference/functions/_regex_string_list.md
      - cot : reference/functions/cot.md
      - create_from_lammps_file_data : reference/functions/create_from_lammps_file_data.md
      - create_from_siesta_file_data : reference/functions/create_from_siesta_file_data.md
      - create_from_turbomole_file_data : reference/functions/create_from_turbomole_file_data.md
      - create_from_vasp_file_data : reference/functions/create_from_vasp_file_data.md
      - create_from_xsf_file_data : reference/functions/create_from_xsf_file_data.md
      - create_from_xyz_file_data : reference/functions/create_from_xyz_file_data.md
      - csc : reference/functions/csc.md
      - generate_lammps : reference/functions/generate_lammps.md
      - islammpslist : reference/functions/islammpslist.md
      - issiestalist : reference/functions/issiestalist.md
      - isturbomolelist : reference/functions/isturbomolelist.md
      - isvasplist : reference/functions/isvasplist.md
      - isxsflist : reference/functions/isxsflist.md
      - isxyzlist : reference/functions/isxyzlist.md
      - read_lammps : reference/functions/read_lammps.md
      - read_siesta : reference/functions/read_siesta.md
      - read_turbomole : reference/functions/read_turbomole.md
      - read_vasp : reference/functions/read_vasp.md
      - read_xsf : reference/functions/read_xsf.md
      - read_xyz : reference/functions/read_xyz.md
      - sec : reference/functions/sec.md





theme:
  name: material
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigate.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:jeremynschroeder@gmail.com
    - icon: fontawesome/solid/t
      link: https://www.depts.ttu.edu/me/combustionlab/
    - icon: fontawesome/brands/github
      link: https://github.com/jerschro

copyright: |
  &copy; 2024 Jeremy Schroeder